services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
        - .env
    volumes:
      - .:/usr/src/app
    command: npm run start
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
  redis: # Name of container
    image: redis
    ports:
      - 6379:6379
    volumes: 
      - redis:/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: otterdatabase
    ports: 
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  docker-nest-postgres:
  redis:
    driver: local